openapi: 3.0.3
info:
  title: GuildHack
  description: GuildHack の API
  version: 1.0.0
servers:
  - url: 'http://localhost:1991/v1'
paths:
  /users:
    get:
      summary: ユーザのリストを取得する
      tags:
        - User
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LIstUser'
      operationId: get-user
      description: ''
    parameters: []
    post:
      summary: 新しいユーザを作成する
      operationId: post-users
      responses:
        '201':
          description: Created
          headers: {}
      description: ''
      tags:
        - User
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
        description: 作成するユーザのオブジェクト
  /recruits:
    get:
      summary: 募集のリストを取得する
      tags:
        - Recruit
      responses: {}
      operationId: get-recruits
      description: ''
    post:
      summary: 新しい募集を作成する
      operationId: post-recruits
      responses:
        '200':
          description: OK
      description: ''
      tags:
        - Recruit
tags:
  - name: Recruit
  - name: User
components:
  schemas:
    User:
      title: User
      type: object
      description: ユーザの情報
      x-examples: {}
      properties:
        id:
          type: integer
          format: int64
        uid:
          type: string
        name:
          type: string
        email:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
    LIstUser:
      title: LIstUser
      type: object
      properties:
        users:
          $ref: '#/components/schemas/User'
      description: ユーザ情報のリスト
    CreateUserRequest:
      title: CreateUserRequest
      type: object
      properties:
        uid:
          type: string
        name:
          type: string
        email:
          type: string
      description: ユーザ登録時のリクエスト
    CreateUserResponse:
      title: CreateUserResponse
      type: object
      description: ユーザ登録時のレスポンス
      properties:
        id:
          type: string
        uid:
          type: string
        name:
          type: string
        email:
          type: string
    Recruit:
      title: Recruit
      type: object
      description: 募集の情報
      properties:
        id:
          type: integer
          format: int64
        user_id:
          type: integer
          format: int64
        title:
          type: string
        event_day:
          type: string
        day:
          type: string
        organizer:
          type: string
        commit:
          type: string
        beginner:
          type: string
        message:
          type: string
        slack_url:
          type: string
        reword:
          type: string
