// Code generated by go-swagger; DO NOT EDIT.

package generated_swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateMemberRequest CreateMemberRequest
//
// 募集の参加者作成時のリクエスト
//
// swagger:model CreateMemberRequest
type CreateMemberRequest struct {

	// 参加者のポジション
	// Example: frontend
	// Required: true
	// Enum: [frontend backend infra]
	Position *string `json:"position"`

	// 参加する募集のid
	// Example: 111
	// Required: true
	RecruitID *int64 `json:"recruit_id"`

	// 参加者のid
	// Example: 212
	// Required: true
	UserID *int64 `json:"user_id"`
}

// Validate validates this create member request
func (m *CreateMemberRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePosition(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRecruitID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUserID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var createMemberRequestTypePositionPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["frontend","backend","infra"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		createMemberRequestTypePositionPropEnum = append(createMemberRequestTypePositionPropEnum, v)
	}
}

const (

	// CreateMemberRequestPositionFrontend captures enum value "frontend"
	CreateMemberRequestPositionFrontend string = "frontend"

	// CreateMemberRequestPositionBackend captures enum value "backend"
	CreateMemberRequestPositionBackend string = "backend"

	// CreateMemberRequestPositionInfra captures enum value "infra"
	CreateMemberRequestPositionInfra string = "infra"
)

// prop value enum
func (m *CreateMemberRequest) validatePositionEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, createMemberRequestTypePositionPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CreateMemberRequest) validatePosition(formats strfmt.Registry) error {

	if err := validate.Required("position", "body", m.Position); err != nil {
		return err
	}

	// value enum
	if err := m.validatePositionEnum("position", "body", *m.Position); err != nil {
		return err
	}

	return nil
}

func (m *CreateMemberRequest) validateRecruitID(formats strfmt.Registry) error {

	if err := validate.Required("recruit_id", "body", m.RecruitID); err != nil {
		return err
	}

	return nil
}

func (m *CreateMemberRequest) validateUserID(formats strfmt.Registry) error {

	if err := validate.Required("user_id", "body", m.UserID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create member request based on context it is used
func (m *CreateMemberRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateMemberRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateMemberRequest) UnmarshalBinary(b []byte) error {
	var res CreateMemberRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
