// Code generated by go-swagger; DO NOT EDIT.

package generated_swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateMemberResponse CreateMemberResponse
//
// 募集の参加者作成時のレスポンス
//
// swagger:model CreateMemberResponse
type CreateMemberResponse struct {

	// 参加者の作成日時
	CreatedAt string `json:"created_at,omitempty"`

	// 参加者のポジション
	// Example: frontend
	// Enum: [frontend backend infra]
	Position string `json:"position,omitempty"`

	// 参加する募集のid
	// Example: 111
	RecruitID int64 `json:"recruit_id,omitempty"`

	// 参加者の更新日時
	UpdatedAt string `json:"updated_at,omitempty"`

	// 参加者のid
	// Example: 212
	UserID int64 `json:"user_id,omitempty"`
}

// Validate validates this create member response
func (m *CreateMemberResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePosition(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var createMemberResponseTypePositionPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["frontend","backend","infra"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		createMemberResponseTypePositionPropEnum = append(createMemberResponseTypePositionPropEnum, v)
	}
}

const (

	// CreateMemberResponsePositionFrontend captures enum value "frontend"
	CreateMemberResponsePositionFrontend string = "frontend"

	// CreateMemberResponsePositionBackend captures enum value "backend"
	CreateMemberResponsePositionBackend string = "backend"

	// CreateMemberResponsePositionInfra captures enum value "infra"
	CreateMemberResponsePositionInfra string = "infra"
)

// prop value enum
func (m *CreateMemberResponse) validatePositionEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, createMemberResponseTypePositionPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CreateMemberResponse) validatePosition(formats strfmt.Registry) error {
	if swag.IsZero(m.Position) { // not required
		return nil
	}

	// value enum
	if err := m.validatePositionEnum("position", "body", m.Position); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this create member response based on context it is used
func (m *CreateMemberResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateMemberResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateMemberResponse) UnmarshalBinary(b []byte) error {
	var res CreateMemberResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
